### ISSUE TITLE
Sophie is still alive

### ISSUE THREAD

**Issue by soph-e** [ConjureETS/DeathBook#1] opened 2015-08-12 00:18 UTC
This is a very serious problem. She must die :8ball:

**Comment by PatriceVignola** [comment] 2015-08-12 00:20
Taking care of this tomorrow :@

**Comment by RosimInc** [comment] 2015-08-12 13:10
Duplicate of issue #0001 from TheGrandSupreme/BucketList

**Closed as completed by RosimInc** 2015-08-12 13:10 UTC
Labels: bug, help wanted
